#!/bin/bash
OutFileName="concat/all.csv"                       # Fix the output name
i=0                                       # Reset a counter
for filename in ./*.csv; do 
 if [ "$filename"  != "$OutFileName" ] ;      # Avoid recursion 
 then 
   if [[ $i -eq 0 ]] ; then 
      head -1  "$filename" >   "$OutFileName" # Copy header if it is the first file
   fi
   tail -n +2  "$filename" >>  "$OutFileName" # Append from the 2nd line each file
   i=$(( $i + 1 ))                            # Increase the counter
echo -e "\n" >> concat/all.csv
 fi
done
echo -e "\ncliend_id" >> concat/all.csv
for f in *.csv; do
    echo "${f%.csv}" >> concat/all.csv
done
tar -zcvf all.tar.gz concat/all.csv
